GET http://localhost:3000/item
###

GET   http://localhost:3000/item/2
###

POST http://localhost:3000/item
Content-Type: application/json

{
    "id":1,
    "name":"margarita2"
}
###


PATCH  http://localhost:3000/item/2
Content-Type: application/json

{
    "name":"wa"
}
###

DELETE  http://localhost:3000/item/2
Content-Type: application/json

{
    "name":"a"
}